/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v{version}/jobs/{jobId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationResponse"][];
                        "application/json": components["schemas"]["ApplicationResponse"][];
                        "text/json": components["schemas"]["ApplicationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitApplicationRequest"];
                    "text/json": components["schemas"]["SubmitApplicationRequest"];
                    "application/*+json": components["schemas"]["SubmitApplicationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationResponse"];
                        "application/json": components["schemas"]["ApplicationResponse"];
                        "text/json": components["schemas"]["ApplicationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/applicants/{applicantId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicantId: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationResponse"][];
                        "application/json": components["schemas"]["ApplicationResponse"][];
                        "text/json": components["schemas"]["ApplicationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/applications/{jobListingId}/{applicantId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update application status
         * @description Updates the status of a job application. Legal status transitions: Submitted → UnderReview, UnderReview → Interviewed, Interviewed → Offered, Offered → Accepted or Rejected, any status → Withdrawn. An illegal transition returns 422 Unprocessable Entity.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                    applicantId: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateApplicationStatusRequest"];
                    "text/json": components["schemas"]["UpdateApplicationStatusRequest"];
                    "application/*+json": components["schemas"]["UpdateApplicationStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationResponse"];
                        "application/json": components["schemas"]["ApplicationResponse"];
                        "text/json": components["schemas"]["ApplicationResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v{version}/applications/{jobListingId}/{applicantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobListingId: string;
                    applicantId: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationResponse"];
                        "application/json": components["schemas"]["ApplicationResponse"];
                        "text/json": components["schemas"]["ApplicationResponse"];
                    };
                };
                /** @description Not Modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/jobs/{jobId}/applications/{applicantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    requestingApplicantId?: string;
                };
                header?: never;
                path: {
                    jobId: string;
                    applicantId: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/applicant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all job listings
         * @description Returns a paginated list of active job listings. The total number of results is included in the X-Total-Count response header. Default page size is 20. Available sort options: postedAt, salaryMin, salaryMax, title.
         */
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                    location?: string;
                    employmentType?: string;
                    salaryMin?: number | string;
                    salaryMax?: number | string;
                    companyId?: string;
                    sort?: string;
                    dir?: string;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfJobResponse"];
                        "application/json": components["schemas"]["PagedResponseOfJobResponse"];
                        "text/json": components["schemas"]["PagedResponseOfJobResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateJobRequest"];
                    "text/json": components["schemas"]["CreateJobRequest"];
                    "application/*+json": components["schemas"]["CreateJobRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobResponse"];
                        "application/json": components["schemas"]["JobResponse"];
                        "text/json": components["schemas"]["JobResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a job listing by ID
         * @description Returns a single active job listing by its unique identifier. Supports ETags for conditional requests: the ETag value is returned in the response header. Send If-None-Match with the ETag value on subsequent requests; the server returns 304 Not Modified when the resource has not changed, saving bandwidth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobResponse"];
                        "application/json": components["schemas"]["JobResponse"];
                        "text/json": components["schemas"]["JobResponse"];
                    };
                };
                /** @description Not Modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateJobRequest"];
                    "text/json": components["schemas"]["UpdateJobRequest"];
                    "application/*+json": components["schemas"]["UpdateJobRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobResponse"];
                        "application/json": components["schemas"]["JobResponse"];
                        "text/json": components["schemas"]["JobResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateJobListingRequest"];
                    "text/json": components["schemas"]["UpdateJobListingRequest"];
                    "application/*+json": components["schemas"]["UpdateJobListingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobResponse"];
                        "application/json": components["schemas"]["JobResponse"];
                        "text/json": components["schemas"]["JobResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v{version}/jobs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text job search
         * @description Searches active job listings by keyword. This endpoint is rate-limited to 30 requests per 60-second sliding window per IP. Exceeding the limit returns 429 Too Many Requests with a Retry-After header.
         */
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobResponse"][];
                        "application/json": components["schemas"]["JobResponse"][];
                        "text/json": components["schemas"]["JobResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/jobs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    companyId?: string;
                };
                header?: never;
                path: {
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobListingStatsResponse"];
                        "application/json": components["schemas"]["JobListingStatsResponse"];
                        "text/json": components["schemas"]["JobListingStatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationResponse: {
            /** Format: uuid */
            jobListingId?: string;
            /** Format: uuid */
            applicantId?: string;
            applicantName?: string;
            /** Format: date-time */
            submittedAt?: string;
            status?: components["schemas"]["ApplicationStatus"];
            phone?: null | string;
            coverLetter?: null | string;
            /** Format: int32 */
            yearsOfExperience?: null | number | string;
            linkedInUrl?: null | string;
            availableImmediately?: null | boolean;
            /** Format: int32 */
            noticePeriodWeeks?: null | number | string;
        };
        ApplicationStatus: number;
        CreateJobRequest: {
            title: string;
            /** Format: uuid */
            companyId: string;
            location: string;
            description: string;
            type: components["schemas"]["JobType"];
            /** Format: double */
            salaryMin?: null | number | string;
            /** Format: double */
            salaryMax?: null | number | string;
            /** Format: date-time */
            closingDate: string;
        };
        JobListingStatsResponse: {
            /** Format: uuid */
            listingId?: string;
            title?: string;
            /** Format: int32 */
            totalApplications?: number | string;
            /** Format: int32 */
            rank?: number | string;
            /** Format: int32 */
            submitted?: number | string;
            /** Format: int32 */
            underReview?: number | string;
            /** Format: int32 */
            shortlisted?: number | string;
            /** Format: int32 */
            rejected?: number | string;
            /** Format: int32 */
            offered?: number | string;
        };
        JobResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            companyName?: string;
            location?: string;
            type?: components["schemas"]["JobType"];
            /** Format: double */
            salaryMin?: null | number | string;
            /** Format: double */
            salaryMax?: null | number | string;
            /** Format: date-time */
            postedAt?: string;
            salaryDisplay?: string;
            /** Format: date-time */
            closingDate?: string;
            /** Format: int32 */
            applicationCount?: number | string;
        };
        JobType: number;
        LoginRequest: {
            username: string;
            password: string;
        };
        PagedResponseOfJobResponse: {
            data?: components["schemas"]["JobResponse"][];
            /** Format: int32 */
            page?: number | string;
            /** Format: int32 */
            pageSize?: number | string;
            /** Format: int32 */
            totalCount?: number | string;
            /** Format: int32 */
            totalPages?: number | string;
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RegisterRequest: {
            fullName: string;
            email: string;
            password: string;
        };
        SubmitApplicationRequest: {
            /** Format: uuid */
            applicantId: string;
            phone?: null | string;
            coverLetter?: null | string;
            /** Format: int32 */
            yearsOfExperience?: null | number | string;
            /** Format: uri */
            linkedInUrl?: null | string;
            availableImmediately?: null | boolean;
            /** Format: int32 */
            noticePeriodWeeks?: null | number | string;
        };
        UpdateApplicationStatusRequest: {
            status?: components["schemas"]["ApplicationStatus"];
        };
        UpdateJobListingRequest: {
            title?: null | string;
            description?: null | string;
            location?: null | string;
            employmentType?: null | string;
            /** Format: double */
            salaryMin?: null | number | string;
            /** Format: double */
            salaryMax?: null | number | string;
            /** Format: date-time */
            expiresAt?: null | string;
        };
        UpdateJobRequest: {
            title: string;
            /** Format: uuid */
            companyId: string;
            location: string;
            description: string;
            type: components["schemas"]["JobType"];
            /** Format: double */
            salaryMin?: null | number | string;
            /** Format: double */
            salaryMax?: null | number | string;
            /** Format: date-time */
            closingDate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
